# Generated by Django 4.0.3 on 2022-04-18 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('jadwal_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_mulai_pembayaran', models.DateField()),
                ('tanggal_akhir_pembayaran', models.DateField()),
                ('tanggal_mulai_penyaluran', models.DateField()),
                ('tanggal_akhir_penyaluran', models.DateField()),
                ('harga_beras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('pengguna_id', models.AutoField(primary_key=True, serialize=False)),
                ('peran', models.IntegerField(choices=[(0, 'Admin'), (1, 'Pemberi')])),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nama', models.CharField(max_length=500, null=True)),
                ('nomor_hp', models.CharField(max_length=500, null=True)),
                ('nomor_kk', models.CharField(max_length=500, null=True)),
                ('alamat', models.CharField(max_length=500, null=True)),
                ('jumlah_anggota_keluarga', models.IntegerField(null=True)),
                ('foto', models.CharField(max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Gagal'), (1, 'Menunggu'), (2, 'Diterima')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penerima',
            fields=[
                ('penerima_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=500)),
                ('nomor_kk', models.CharField(max_length=500)),
                ('alamat', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(0, 'Gagal'), (1, 'Menunggu'), (2, 'Diterima')])),
                ('jadwal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZakatApp.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('pembayaran_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nominal', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Gagal'), (1, 'Menunggu'), (2, 'Diterima')])),
                ('jadwal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ZakatApp.jadwal')),
                ('pemberi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZakatApp.pengguna')),
            ],
        ),
    ]
