# Generated by Django 3.2.4 on 2022-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZakatApp', '0002_auto_20220519_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='alamat',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='jumlah_anggota_keluarga',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='nama',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='nomor_hp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='nomor_kk',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
